### ISSUE TITLE
console is in jibrish 

### ISSUE THREAD

**Issue by limelect** [JensBorrisholt/Holidays#2]
console is in jibrish 
D10.2.3  in Israel consol fonts ?

![Screenshot - 14_04_2019 , 10_19_50](https://user-images.githubusercontent.com/4199131/56089637-ac4bc000-5e9e-11e9-8d64-0650f08acbc7.png)

**Comment by limelect** [comment]
my components
http://limelect.com/downloads/hebrew-holydays-delphi-components/

![Screenshot - 20_03_2019 , 12_01_28](https://user-images.githubusercontent.com/4199131/56089665-15333800-5e9f-11e9-8ebf-e2e952a06a60.png)

**Comment by JensBorrisholt** [comment]
Codepage is out of scope for calendar calculations.

As far as I know the Hebrew calendar is not based on Easter

**Comment by JensBorrisholt** [comment]
System.Console updated with support for unicode.

**Comment by limelect** [comment]
still gibberish
