### ISSUE TITLE
console is in jibrish

### ISSUE THREAD

**Issue by limelect** [JensBorrisholt/Holidays#4]
console is in jibrish still the same.

**Comment by limelect** [comment]
This is after updating both holiday and EasyConsole-master

**Comment by JensBorrisholt** [comment]
I guess you don't have the newest version system.console

**Comment by limelect** [comment]
Just down loaded YOUR EasyConsole-master !!!! am i wrong?

**Comment by JensBorrisholt** [comment]
Yes.  😁

First of all system.console should have been included in the project. I don't have time to do that to night.

So get an updated version of it form Delphi Console 

https://github.com/JensBorrisholt/DelphiConsole

**Comment by JensBorrisholt** [comment]
The console project is for sure unicode ready. I have tested it with  Cyrillic letters. If your Hebrew letters still doesn't shot it's because you have choose the right font.
